### ISSUE TITLE
ThreatPinch Lookup for Firefox?

### ISSUE THREAD

**Issue by cloudtracer** [mazen160/Firefox-Security-Toolkit#5]
ThreatPinch Lookup might make a good addition to the list of extensions.

https://addons.mozilla.org/en-US/firefox/addon/threatpinch-lookup-for-firefox/

*Disclaimer: ThreatPinch Lookup is a tool that I maintain.

**Comment by mazen160** [comment]
Hi @cloudtracer ,

Thanks  for the addition!

I have added ThreatPinch Lookup to Firefox Security Toolkit.

https://github.com/mazen160/Firefox-Security-Toolkit/commit/751cda15086b7137543d2222d623b6cfccdf21cc

Keep up the great work! :)

Thanks again,
Mazin

**Comment by geekscrapy** [comment]
Looks like it's no longer available for firefox?

**Comment by mazen160** [comment]
Hi @geekscrapy 

Yes, it seems to be deleted from Firefox Add-ons store.

We generally need to do a full update that is focused on Firefox Quantum.

Best,
Mazin
