### ISSUE TITLE
Missing/Dead addons

### ISSUE THREAD

**Issue by DenverDaveH** [mazen160/Firefox-Security-Toolkit#7]
Hello,
After my initial excitement at finding this tool, this is to let you know that most of the addons are dead/gone.

I can reinstall if you want a list? 

Or are you going to archive this and prevent further downloads?

Just curious

**Comment by mazen160** [comment]
Hi @DenverDaveH 

Please send me an updated list of what's broken/dead, and I would be happy to push it to the project.

Also, please try the tool on waterfox instead. Most of the add-ons should be working normally.

Best Regards,
Mazin

**Comment by DenverDaveH** [comment]
Hi Mazin,
Let me install Waterfox on my testing vm and let you know.
And it would be easier to let you know what did install vs did not install:
Disable WebRTC
Flagfox
forms hub
Greasemonkey
Rested
Wappalyzer
WebDeveloper

Is there a way to specify a different browser? Or just install the addons manually? Thanks for the pointer.
Dave

**Comment by mazen160** [comment]
Hi Dave,

Please try the following: 
https://github.com/mazen160/Firefox-Security-Toolkit/blob/master/firefox_security_toolkit.sh#L86

Change the path from '/usr/bin/firefox' to '/path/to/waterfox-binary' and it should work similarly.

Based on that, you should have a relatively better experience. I will be updating the tool based on your input when possible for new/updated add-ons.

Best Regards,
Mazin

**Comment by DenverDaveH** [comment]
Hi Mazin,
Per your instrucitions, I have installed Waterfox. I then made the change to the sh script and I got a lot of new tabs in WF! Howerver the  news is not so good. The following were not installed:
*advanced-dork.xpi              
*cookie_export_import.xpi        
*cookiemanager+.xpi              
*copy_as_plain_text.xpi          
*crypto_fox.xpi                  
*csrf_finder.xpi                 
*firebug.xpi                     
*fireforce.xpi                   
flagfox.xpi                     
*foxy_proxy.xpi                  
*hackbar.xpi                    
*javascript_deobfuscator.xpi
*live_http_headers.xpi
*passiverecon.xpi
*regular-expressions-tester.xpi
*right_click_xss.xpi
*shodan.xpi
*tamper_data.xpi
*threatpinch-lookup.xpi
*useragentswitcher.xml
*user_agent_switcher.xpi

Additionally, the following are not compatible with FF 56.2.14:
Flagfox 6.1.17
Greasemonkey 4.9
Wappalyzer 5.8.4

Let me know what more I can do to help.

Sincerely,
Dave

**Comment by DenverDaveH** [comment]
Hello,
Should we consider this project as dead/abandoned? 
Just curious :)

**Comment by mazen160** [comment]
Hi @DenverDaveH 

I hope everything is going well with you.

I have updated firefox-security-toolkit today with new addons, updated addons, and removed all unsupported ones for the latest version of Firefox.

It should be much better now!

Please check the new release, and feel free to let me know if there is anything that needs to be changed!

Best regards,
Mazin
